# Generated by Django 5.0.4 on 2024-04-21 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=255)),
                ('kod', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Praca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=50)),
                ('datum_zaciatku', models.DateField(verbose_name='datum zaciatku')),
                ('datum_ukoncenia', models.DateField(verbose_name='datum ukoncenia')),
                ('popis_prace', models.TextField()),
                ('naklady', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=100)),
                ('popis', models.TextField()),
                ('adresa', models.CharField(max_length=30)),
                ('psc', models.CharField(max_length=10)),
                ('mesto', models.CharField(max_length=20)),
                ('stat', models.CharField(max_length=30)),
                ('datum_zaciatku', models.DateField(verbose_name='datum zaciatku')),
                ('datum_ukoncenia', models.DateField(blank=True, null=True, verbose_name='datum ukoncenia')),
                ('stav', models.CharField(max_length=50)),
                ('celkovy_rozpocet', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Zakaznici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno', models.CharField(max_length=50)),
                ('priezvisko', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=20)),
                ('typ_osoby', models.CharField(choices=[('F', 'Fyzická osoba'), ('P', 'Právnická osoba')], max_length=1)),
                ('nazov_firmy', models.CharField(blank=True, max_length=50, null=True)),
                ('ico', models.CharField(blank=True, max_length=20, null=True)),
                ('dic', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zamestnanec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno', models.CharField(max_length=50)),
                ('priezvisko', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=20)),
                ('adresa_bydliska', models.CharField(max_length=30)),
                ('psc', models.CharField(max_length=10)),
                ('mesto_bydliska', models.CharField(max_length=20)),
                ('stat_bydliska', models.CharField(max_length=30)),
                ('datum_nastupu', models.DateField(verbose_name='datum nastupu')),
                ('kvalifikacie', models.TextField()),
                ('role', models.CharField(choices=[('V', 'Vedúci podniku'), ('H', 'Hlavný zamestnanec'), ('Z', 'Zamestnanec')], max_length=1)),
                ('heslo', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='PouzityMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnozstvo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jednotkova_cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stavMat.material')),
                ('praca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stavMat.praca')),
            ],
        ),
        migrations.AddField(
            model_name='praca',
            name='projekt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stavMat.projekt'),
        ),
        migrations.CreateModel(
            name='Faktura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_vystavenia', models.DateField(auto_now_add=True, verbose_name='datum vystavenia')),
                ('datum_splatnosti', models.DateField(verbose_name='datum splatnosti')),
                ('suma', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stav_platby', models.CharField(max_length=20)),
                ('projekt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stavMat.projekt')),
            ],
        ),
        migrations.AddField(
            model_name='projekt',
            name='zakaznik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stavMat.zakaznici'),
        ),
        migrations.AddField(
            model_name='praca',
            name='zamestnanec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stavMat.zamestnanec'),
        ),
    ]
