# Generated by Django 5.0.4 on 2024-04-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stavMat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktura',
            name='stav_platby',
            field=models.CharField(choices=[('U', 'Uhradená'), ('N', 'Neuhradená')], max_length=20),
        ),
    ]
