# Generated by Django 5.0.4 on 2024-04-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stavMat', '0002_alter_faktura_stav_platby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projekt',
            name='stav',
            field=models.CharField(choices=[('U', 'Ukončený'), ('N', 'Neukončený')], max_length=50),
        ),
    ]
