# Generated by Django 5.0.4 on 2024-04-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stavMat', '0003_alter_projekt_stav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praca',
            name='datum_ukoncenia',
            field=models.DateField(blank=True, null=True, verbose_name='datum ukoncenia'),
        ),
    ]
