# Generated by Django 5.0.4 on 2024-04-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stavMat', '0004_alter_praca_datum_ukoncenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamestnanec',
            name='kvalifikacie',
            field=models.TextField(blank=True, null=True),
        ),
    ]
