# Generated by Django 5.0.4 on 2024-04-26 14:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stavMat', '0005_alter_zamestnanec_kvalifikacie'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaznici',
            name='prihlasovacie_heslo',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zakaznici',
            name='prihlasovacie_meno',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
