# Generated by Django 5.0.4 on 2024-04-27 14:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stavMat', '0006_zakaznici_prihlasovacie_heslo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zamestnanec',
            old_name='heslo',
            new_name='prihlasovacie_heslo',
        ),
        migrations.AddField(
            model_name='zamestnanec',
            name='prihlasovacie_meno',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
