# Generated by Django 5.0.4 on 2024-04-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stavMat', '0007_rename_heslo_zamestnanec_prihlasovacie_heslo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zakaznici',
            old_name='telefon',
            new_name='telefón',
        ),
    ]
