# Generated by Django 5.0.4 on 2024-04-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stavMat', '0008_rename_telefon_zakaznici_telefón'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zakaznici',
            old_name='dic',
            new_name='dič',
        ),
        migrations.RenameField(
            model_name='zakaznici',
            old_name='ico',
            new_name='ičo',
        ),
        migrations.RenameField(
            model_name='zakaznici',
            old_name='nazov_firmy',
            new_name='názov_firmy',
        ),
    ]
