# Generated by Django 5.0.4 on 2024-04-27 15:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stavMat', '0009_rename_dic_zakaznici_dič_rename_ico_zakaznici_ičo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zakaznici',
            name='dič',
        ),
        migrations.RemoveField(
            model_name='zakaznici',
            name='ičo',
        ),
        migrations.RemoveField(
            model_name='zakaznici',
            name='názov_firmy',
        ),
        migrations.RemoveField(
            model_name='zakaznici',
            name='telefón',
        ),
        migrations.AddField(
            model_name='zakaznici',
            name='dic',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DIČ'),
        ),
        migrations.AddField(
            model_name='zakaznici',
            name='ico',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='IČO'),
        ),
        migrations.AddField(
            model_name='zakaznici',
            name='nazov_firmy',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Názov firmy'),
        ),
        migrations.AddField(
            model_name='zakaznici',
            name='telefon',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='Telefón'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faktura',
            name='datum_vystavenia',
            field=models.DateField(auto_now_add=True, verbose_name='Dátum vystavenia'),
        ),
        migrations.AlterField(
            model_name='material',
            name='kod',
            field=models.CharField(max_length=50, verbose_name='Kód'),
        ),
        migrations.AlterField(
            model_name='material',
            name='nazov',
            field=models.CharField(max_length=255, verbose_name='Názov'),
        ),
        migrations.AlterField(
            model_name='pouzitymaterial',
            name='jednotkova_cena',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jednotková cena'),
        ),
        migrations.AlterField(
            model_name='pouzitymaterial',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stavMat.material', verbose_name='Materiál'),
        ),
        migrations.AlterField(
            model_name='pouzitymaterial',
            name='mnozstvo',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Množstvo'),
        ),
        migrations.AlterField(
            model_name='pouzitymaterial',
            name='praca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stavMat.praca', verbose_name='Práca'),
        ),
        migrations.AlterField(
            model_name='praca',
            name='datum_ukoncenia',
            field=models.DateField(blank=True, null=True, verbose_name='Dátum ukončenia'),
        ),
        migrations.AlterField(
            model_name='praca',
            name='datum_zaciatku',
            field=models.DateField(verbose_name='Dátum začiatku'),
        ),
        migrations.AlterField(
            model_name='praca',
            name='naklady',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Náklady'),
        ),
        migrations.AlterField(
            model_name='praca',
            name='popis_prace',
            field=models.TextField(verbose_name='Popis práce'),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='celkovy_rozpocet',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Celkový rozpočet'),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='datum_ukoncenia',
            field=models.DateField(blank=True, null=True, verbose_name='Dátum ukončenia'),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='datum_zaciatku',
            field=models.DateField(verbose_name='Dátum začiatku'),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='nazov',
            field=models.CharField(max_length=100, verbose_name='Názov'),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='psc',
            field=models.CharField(max_length=10, verbose_name='PSČ'),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='stat',
            field=models.CharField(max_length=30, verbose_name='Štát'),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='zakaznik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stavMat.zakaznici', verbose_name='Zákazník'),
        ),
        migrations.AlterField(
            model_name='zamestnanec',
            name='datum_nastupu',
            field=models.DateField(verbose_name='Dátum nástupu'),
        ),
        migrations.AlterField(
            model_name='zamestnanec',
            name='kvalifikacie',
            field=models.TextField(blank=True, null=True, verbose_name='Kvalifikácie'),
        ),
        migrations.AlterField(
            model_name='zamestnanec',
            name='psc',
            field=models.CharField(max_length=10, verbose_name='PSČ'),
        ),
        migrations.AlterField(
            model_name='zamestnanec',
            name='stat_bydliska',
            field=models.CharField(max_length=30, verbose_name='Štát bydliska'),
        ),
        migrations.AlterField(
            model_name='zamestnanec',
            name='telefon',
            field=models.CharField(max_length=20, verbose_name='Telefón'),
        ),
    ]
